name: systemd-units

on:
  pull_request:
    paths:
      - "systemd/**"
  push:

jobs:
  verify-units:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9.6
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          dnf install -qy podman systemd
      - name: Verify units
        run: |
          mkdir -p /etc/containers/systemd/
          cp systemd/*.container /data/systemd/*.network /etc/containers/systemd/
          cp systemd/*.socket /etc/systemd/system/
          for file in /etc/containers/systemd/*.container; do
            unit=$(basename "$file" .container)
            echo "# verify $unit"
            systemd-analyze --generators=true verify "$unit.service" ||
            touch /tmp/RC.tmp
          done
          ! test -r /tmp/RC.tmp
