name: systemd-units

on:
  pull_request:
    paths:
      - "systemd/**"
  push:

jobs:
  verify-units:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install systemd tools
        run: |
          sudo apt-get update
          sudo apt-get install -y podman systemd

      - name: Verify systemd unit files
        run: |
          set -e
          sudo cp systemd/* /etc/containers/systemd
          for file in systemd/*.container; do
            echo "Verifying $unit"
            unit=$(basename "$file" .container)
            systemd-analyze --generators=true verify "$unit.service"
          done
