name: systemd-units

on:
  pull_request:
    paths:
      - "systemd/**"
  push:

jobs:
  verify-units:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9.6
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          dnf install -qy podman systemd
      - name: Prepare
        run: |
          set -e
          mkdir -p \
            ~/.config/containers/systemd/ \
            ~/.config/systemd/user/
          cp \
            systemd/*.container \
            systemd/*.network \
            ~/.config/containers/systemd/
          cp \
            systemd/*.socket \
            ~/.config/systemd/system/
      - name: Verify units
        run: |
          set -e
          for file in ~/.config/containers/systemd/*.container; do
            unit=$(basename "$file" .container)
            echo "# verify $unit"
            systemd-analyze --generators=true --user verify "$unit.service" ||
            touch /tmp/RC.tmp
          done
          ! test -r /tmp/RC.tmp
