name: systemd-units

on:
  pull_request:
    paths:
      - "systemd/**"
  push:

jobs:
  verify-units:
    runs-on: ubuntu-latest
    container:
      image: almalinux
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v6
      - name: Verify units
        run: |
          set -ex
          mkdir -p /etc/containers/systemd/
          cp /data/systemd/*.container /data/systemd/*.network /etc/containers/systemd/
          cp /data/systemd/*.socket /etc/systemd/system/
          dnf install -y podman systemd
          for file in /etc/containers/systemd/*.container; do
            unit=$(basename "$file" .container)
            systemd-analyze --generators=true verify "${unit%@}.service"
          done
