name: systemd-units

on:
  pull_request:
    paths:
      - "systemd/**"
  push:

jobs:
  verify-units:
    runs-on: ubuntu-latest
    container:
      image: almalinux
      volumes:
        - ${{ github.workspace }}:/etc/containers/systemd/systemd
    steps:
      - uses: actions/checkout@v6
      - name: Verify units
        run: |
          set -x
          find /etc/containers/systemd/systemd -ls
          dnf install -y podman systemd
          for file in /etc/containers/systemd/systemd/*.container; do
            unit=$(basename "$file" .container)
            systemd-analyze --generators=true verify "${unit%@}.service"
          done
